### ISSUE TITLE
Error when unrolling

### ISSUE THREAD

**Issue by WQR53** [bondhugula/pluto#91]
Hi, sir

I run `./../polycc 1.c --moredebug --nointratileopt --noprevector --unroll` to get unrolling transformation, 
but get type error as follows:
```
[Plorc] Found unroll-jammable nest
Traceback (most recent call last):
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/orcc", line 12, in <module>
    src.main.main.start(sys.argv, src.main.main.C_CPP)
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/main/main.py", line 30, in start
    import ann_parser, cmd_line_opts, opt_driver, tspec.tspec
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/main/opt_driver.py", line 6, in <module>
    import code_frag, dyn_loader, tuner.tuner
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/main/tuner/tuner.py", line 6, in <module>
    import main.dyn_loader, main.tspec.tspec, ptest_codegen_basic, ptest_driver
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/main/tspec/tspec.py", line 6, in <module>
    import eval, parser, tune_info
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/main/tspec/parser.py", line 27, in <module>
    ID          = Token('[A-Za-z_][A-Za-z0-9_]*', group=0) >> f_token
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/tool/ZestyParser/Tokens.py", line 236, in __rshift__
    new = copy.copy(self)
  File "/usr/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
  File "/home/wqr/datadependence/pluto/pluto-0.11.4/orio-0.1.0/src/tool/ZestyParser/Tokens.py", line 186, in __copy__
    n.desc = copy.copy(self.desc)
  File "/usr/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
TypeError: cannot copy this pattern object
[Plorc] Failed to run Orio
```
And my python version is 2.7.17. 

I would be very grateful indeed for any help you could give me.

**Comment by bondhugula** [comment]
Unfortunately, unrolling via `orio` isn't supported or maintained anymore. The errors you are encountering are most likely due to Python version compatibility or API breakage. Patches are however welcome to fix/upgrade.

**Comment by WQR53** [comment]
Thank you for your reply. Could you please tell me which python version I should use? Thank you very much！

**Comment by bondhugula** [comment]
I can't recall which one would work out of the box. Instead of switching to an old Python version, I recommend patching the tool to get it working with the latest version.

**Comment by WQR53** [comment]
Thank you for your advice. I'll try later.
